[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

lib_deps =
    olikraus/U8g2 @ ^2.35.17
    adafruit/Adafruit AHTX0 @ ^2.0.5
    adafruit/Adafruit BusIO @ ^1.16.1

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
